# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Fast rarefaction via sequential hypergeometric sampling
#'
#' For each row, taxa counts are subsampled without replacement to exactly
#' \code{depth} total counts using the sequential hypergeometric algorithm:
#' iterate over taxa and draw from Hypergeometric(m = count_j,
#' n = remaining_pool - count_j, k = remaining_depth), updating both
#' running totals after each taxon. This is O(rows * cols) and produces
#' the same distribution as drawing \code{depth} items uniformly at random
#' without replacement from the pool of individuals.
#'
#' @param otu Numeric matrix of OTU counts (samples x taxa). Row sums must
#'   be >= \code{depth}.
#' @param depth Integer rarefaction depth.
#' @return Integer matrix of rarefied counts with the same dimensions and
#'   dimnames as \code{otu}.
#' @keywords internal
rrarefy_cpp <- function(otu, depth) {
    .Call(`_QsRutils_rrarefy_cpp`, otu, depth)
}

